"""Regenerate the reconstruction basis in as734x-spectrum-card.js from the vendor workbook.

    python3 script/extract-basis.py as734x-golden.xlsx

The workbook holds one column of weights per channel at 1nm. Resampling to STEP nm and
rounding to SIG figures costs under 0.3% of peak and cuts the embedded size about sevenfold.
"""

import re
import sys
import xml.etree.ElementTree as ET
import zipfile

M = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"
R = "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}"
FROM_NM = 380
TO_NM = 1000
STEP = 5
SIG = 4
CARD = "as734x-spectrum-card.js"
BEGIN = "// --- basis: generated by script/extract-basis.py, do not edit ---"
END = "// --- end basis ---"


def column_index(ref):
    letters = "".join(c for c in ref if c.isalpha())
    n = 0
    for c in letters:
        n = n * 26 + ord(c) - 64
    return n - 1


def read_sheet(zf, path, shared):
    rows = []
    for row in ET.fromstring(zf.read(path)).iter(M + "row"):
        cells = {}
        for c in row.iter(M + "c"):
            v = c.find(M + "v")
            if v is None or v.text is None:
                continue
            cells[column_index(c.get("r"))] = shared[int(v.text)] if c.get("t") == "s" else float(v.text)
        rows.append(cells)
    return rows


def main(path):
    zf = zipfile.ZipFile(path)
    shared = [
        "".join(t.text or "" for t in si.iter(M + "t"))
        for si in ET.fromstring(zf.read("xl/sharedStrings.xml"))
    ]
    rels = {r.get("Id"): r.get("Target") for r in ET.fromstring(zf.read("xl/_rels/workbook.xml.rels"))}
    sheets = {
        sh.get("name").lower(): "xl/" + rels[sh.get(R + "id")]
        for sh in ET.fromstring(zf.read("xl/workbook.xml")).find(M + "sheets")
    }

    blocks = []
    for model in sorted(sheets):
        rows = read_sheet(zf, sheets[model], shared)
        header = rows[0]
        columns = [i for i in sorted(header) if i > 0]
        data = [r for r in rows[2:] if 0 in r and FROM_NM <= r[0] <= TO_NM and (r[0] - FROM_NM) % STEP == 0]
        if not data:
            sys.exit(f"{model}: no rows in {FROM_NM}-{TO_NM}nm")

        keys = [str(header[i]).lower() for i in columns]
        weights = []
        for i in columns:
            weights.append("[" + ",".join(f"{r.get(i, 0.0):.{SIG}g}" for r in data) + "]")
        blocks.append(
            f"  {model}: {{\n"
            f"    from: {FROM_NM}, step: {STEP}, count: {len(data)},\n"
            f"    keys: {keys!r},\n".replace("'", '"')
            + "    weights: [\n      " + ",\n      ".join(weights) + ",\n    ],\n  },"
        )
        print(f"{model}: {len(data)} rows x {len(columns)} channels ({', '.join(keys)})", file=sys.stderr)

    generated = BEGIN + "\nconst SPECTRAL_BASIS = {\n" + "\n".join(blocks) + "\n};\n" + END

    source = open(CARD, encoding="utf-8").read()
    if BEGIN in source:
        source = re.sub(re.escape(BEGIN) + ".*?" + re.escape(END), generated, source, flags=re.S)
    else:
        source = generated + "\n\n" + source
    open(CARD, "w", encoding="utf-8").write(source)
    print(f"wrote {len(generated) / 1024:.0f} KB into {CARD}", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "as734x-golden.xlsx")
